export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const PRODUCTS_FAILURE = "PRODUCTS_FAILURE";

export const GET_PRODUCTS_SUCSESS = "GET_PRODUCTS_SUCSESS";
export const POST_PRODUCTS_SUCSESS = "POST_PRODUCTS_SUCSESS";
export const DELETE_PRODUCTS_SUCSESS = "DELETE_PRODUCTS_SUCSESS";
export const PATCH_PRODUCTS_SUCSESS = "PATCH_PRODUCTS_SUCSESS";

//Login

export const LOGIN_REQUEST = "LOGIN_REQUES";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCSESS = "LOGIN_SUCSESS";
export const POST_LOGIN_SUCSESS = "POST_LOGIN_SUCSESS";
